export default [
  // bugs
  {
    cpId: "b-1",
    category: "bug",
    name: "Common Butterfly",
    location: "Flying",
    shadow: null,
    price: 160,
    months: {
      north: [0, 1, 2, 3, 4, 5, 8, 9, 10, 11],
      south: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    },
    times: [{ from: 4, to: 19 }],
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-2",
    category: "bug",
    name: "Yellow Butterfly",
    location: "Flying",
    shadow: null,
    price: 160,
    months: {
      north: [2, 3, 4, 5, 8, 9],
      south: [2, 3, 8, 9, 10, 11],
    },
    times: [{ from: 4, to: 19 }],
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-3",
    category: "bug",
    name: "Tiger Butterfly",
    location: "Flying",
    shadow: null,
    price: 240,
    months: {
      north: [2, 3, 4, 5, 6, 7, 8],
      south: [0, 1, 2, 8, 9, 10, 11],
    },
    times: [{ from: 4, to: 19 }],
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-4",
    category: "bug",
    name: "Peacock Butterfly",
    location: "Flying",
    shadow: null,
    price: 2500,
    months: {
      north: [2, 3, 4, 5],
      south: [8, 9, 10, 11],
    },
    times: [{ from: 4, to: 19 }],
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-5",
    category: "bug",
    name: "Common Bluebottle",
    location: "Flying",
    shadow: null,
    price: 300,
    months: {
      north: [3, 4, 5, 6, 7],
      south: [0, 1, 9, 10, 11],
    },
    times: [{ from: 4, to: 19 }],
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-6",
    category: "bug",
    name: "Paper Kite Butterfly",
    location: "Flying",
    shadow: null,
    price: 1000,
    months: null,
    times: [{ from: 8, to: 19 }],
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-7",
    category: "bug",
    name: "Great Purple Emperor",
    location: "Flying",
    shadow: null,
    price: 3000,
    months: {
      north: [4, 5, 6, 7],
      south: [0, 1, 10, 11],
    },
    times: [{ from: 4, to: 19 }],
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-8",
    category: "bug",
    name: "Monarch Butterfly",
    location: "Flying",
    shadow: null,
    price: 140,
    months: {
      north: [8, 9, 10],
      south: [2, 3, 4],
    },
    times: [{ from: 4, to: 15 }],
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-9",
    category: "bug",
    name: "Emperor Butterfly",
    location: "Flying",
    shadow: null,
    price: 4000,
    months: {
      north: [0, 1, 2, 5, 6, 7, 8],
      south: [0, 1, 2, 5, 6, 7, 8],
    },
    times: [
      { from: 0, to: 8 },
      { from: 17, to: 24 },
    ],
    rainOnly: false,
    rainHide: true,
    rarity: 2,
  },
  {
    cpId: "b-10",
    category: "bug",
    name: "Agrias Butterfly",
    location: "Flying",
    shadow: null,
    price: 3000,
    months: {
      north: [3, 4, 5, 6, 7, 8],
      south: [0, 1, 2, 9, 10, 11],
    },
    times: [{ from: 8, to: 17 }],
    rainOnly: false,
    rainHide: true,
    rarity: 2,
  },
  {
    cpId: "b-11",
    category: "bug",
    name: "Rajah Brooke's Birdwing",
    location: "Flying",
    shadow: null,
    price: 2500,
    months: {
      north: [0, 1, 3, 4, 5, 6, 7, 8, 11],
      south: [0, 1, 2, 5, 6, 7, 9, 10, 11],
    },
    times: [{ from: 8, to: 17 }],
    rainOnly: false,
    rainHide: true,
    rarity: 2,
  },
  {
    cpId: "b-12",
    category: "bug",
    name: "Queen Alexandra's Birdwing",
    location: "Flying",
    shadow: null,
    price: 4000,
    months: {
      north: [4, 5, 6, 7, 8],
      south: [0, 1, 2, 10, 11],
    },
    times: [{ from: 8, to: 16 }],
    rainOnly: false,
    rainHide: true,
    rarity: 3,
  },
  {
    cpId: "b-13",
    category: "bug",
    name: "Moth",
    location: "Near Lights",
    shadow: null,
    price: 130,
    months: null,
    times: [
      { from: 0, to: 4 },
      { from: 19, to: 24 },
    ],
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-14",
    category: "bug",
    name: "Atlas Moth",
    location: "Trees",
    shadow: null,
    price: 3000,
    months: {
      north: [3, 4, 5, 6, 7, 8],
      south: [0, 1, 2, 9, 10, 11],
    },
    times: [
      { from: 0, to: 4 },
      { from: 19, to: 24 },
    ],
    rainOnly: false,
    rainHide: true,
    rarity: 2,
  },
  {
    cpId: "b-15",
    category: "bug",
    name: "Madagascan Sunset Moth",
    location: "Flying",
    shadow: null,
    price: 2500,
    months: {
      north: [3, 4, 5, 6, 7, 8],
      south: [0, 1, 2, 9, 10, 11],
    },
    times: [{ from: 8, to: 16 }],
    rainOnly: false,
    rainHide: true,
    rarity: 2,
  },
  {
    cpId: "b-16",
    category: "bug",
    name: "Long Locust",
    location: "Ground",
    shadow: null,
    price: 200,
    months: {
      north: [3, 4, 5, 6, 7, 8, 9, 10],
      south: [0, 1, 2, 3, 4, 9, 10, 11],
    },
    times: [{ from: 8, to: 19 }],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-17",
    category: "bug",
    name: "Migratory Locust",
    location: "Ground",
    shadow: null,
    price: 600,
    months: {
      north: [7, 8, 9, 10],
      south: [1, 2, 3, 4],
    },
    times: [{ from: 8, to: 19 }],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-18",
    category: "bug",
    name: "Rice Grasshopper",
    location: "Ground",
    shadow: null,
    price: 400,
    months: {
      north: [7, 8, 9, 10],
      south: [1, 2, 3, 4],
    },
    times: [{ from: 8, to: 19 }],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-19",
    category: "bug",
    name: "Grasshopper",
    location: "Ground",
    shadow: null,
    price: 160,
    months: {
      north: [6, 7, 8],
      south: [0, 1, 2],
    },
    times: [{ from: 8, to: 17 }],
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-20",
    category: "bug",
    name: "Cricket",
    location: "Ground",
    shadow: null,
    price: 130,
    months: {
      north: [8, 9, 10],
      south: [3, 4, 5],
    },
    times: [
      { from: 0, to: 8 },
      { from: 17, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-21",
    category: "bug",
    name: "Bell Cricket",
    location: "Ground",
    shadow: null,
    price: 430,
    months: {
      north: [8, 9],
      south: [2, 3],
    },
    times: [
      { from: 0, to: 8 },
      { from: 17, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-22",
    category: "bug",
    name: "Mantis",
    location: "On Flowers",
    shadow: null,
    price: 430,
    months: {
      north: [2, 3, 4, 5, 6, 7, 8, 9, 10],
      south: [0, 1, 2, 3, 4, 8, 9, 10, 11],
    },
    times: [{ from: 8, to: 17 }],
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-23",
    category: "bug",
    name: "Orchid Mantis",
    location: "On White Flowers",
    shadow: null,
    price: 2400,
    months: {
      north: [2, 3, 4, 5, 6, 7, 8, 9, 10],
      south: [0, 1, 2, 3, 4, 8, 9, 10, 11],
    },
    times: [{ from: 8, to: 17 }],
    rainOnly: false,
    rainHide: true,
    rarity: 3,
  },
  {
    cpId: "b-24",
    category: "bug",
    name: "Honeybee",
    location: "On Flowers",
    shadow: null,
    price: 200,
    months: {
      north: [2, 3, 4, 5, 6],
      south: [0, 8, 9, 10, 11],
    },
    times: [{ from: 8, to: 17 }],
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-25",
    category: "bug",
    name: "Wasp",
    location: "Shake Trees",
    shadow: null,
    price: 2500,
    months: null,
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-26",
    category: "bug",
    name: "Brown Cicada",
    location: "On Trees",
    shadow: null,
    price: 250,
    months: {
      north: [6, 7],
      south: [0, 1],
    },
    times: [{ from: 8, to: 17 }],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-27",
    category: "bug",
    name: "Robust Cicada",
    location: "On Trees",
    shadow: null,
    price: 300,
    months: {
      north: [6, 7],
      south: [0, 1],
    },
    times: [{ from: 8, to: 17 }],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-28",
    category: "bug",
    name: "Giant Cicada",
    location: "On Trees",
    shadow: null,
    price: 500,
    months: {
      north: [6, 7],
      south: [0, 1],
    },
    times: [{ from: 8, to: 17 }],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-29",
    category: "bug",
    name: "Walker Cicada",
    location: "On Trees",
    shadow: null,
    price: 400,
    months: {
      north: [7, 8],
      south: [1, 2],
    },
    times: [{ from: 8, to: 17 }],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-30",
    category: "bug",
    name: "Evening Cicada",
    location: "On Trees",
    shadow: null,
    price: 550,
    months: {
      north: [6, 7],
      south: [0, 1],
    },
    times: [
      { from: 4, to: 8 },
      { from: 16, to: 19 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-31",
    category: "bug",
    name: "Cicada Shell",
    location: "On Trees",
    shadow: null,
    price: 10,
    months: {
      north: [6, 7],
      south: [0, 1],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-32",
    category: "bug",
    name: "Red Dragonfly",
    location: "Flying",
    shadow: null,
    price: 180,
    months: {
      north: [8, 9],
      south: [2, 3],
    },
    times: [{ from: 8, to: 17 }],
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-33",
    category: "bug",
    name: "Darner Dragonfly",
    location: "Flying",
    shadow: null,
    price: 230,
    months: {
      north: [3, 4, 5, 6, 7, 8, 9],
      south: [0, 1, 2, 3, 9, 10, 11],
    },
    times: [{ from: 8, to: 17 }],
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-34",
    category: "bug",
    name: "Banded Dragonfly",
    location: "Flying",
    shadow: null,
    price: 4500,
    months: {
      north: [4, 5, 6, 7, 8, 9],
      south: [0, 1, 2, 3, 10, 11],
    },
    times: [{ from: 8, to: 17 }],
    rainOnly: false,
    rainHide: true,
    rarity: 3,
  },
  {
    cpId: "b-35",
    category: "bug",
    name: "Damselfly",
    location: "Flying",
    shadow: null,
    price: 500,
    months: {
      north: [0, 1, 10, 11],
      south: [4, 5, 6, 7],
    },
    times: null,
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-36",
    category: "bug",
    name: "Firefly",
    location: "Near Rivers",
    shadow: null,
    price: 300,
    months: {
      north: [5],
      south: [11],
    },
    times: [
      { from: 0, to: 4 },
      { from: 15, to: 24 },
    ],
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-37",
    category: "bug",
    name: "Mole Cricket",
    location: "Underground",
    shadow: null,
    price: 500,
    months: {
      north: [0, 1, 2, 3, 4, 10, 11],
      south: [4, 5, 6, 7, 8, 9, 10],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 3,
  },
  {
    cpId: "b-38",
    category: "bug",
    name: "Pondskater",
    location: "On Rivers",
    shadow: null,
    price: 130,
    months: {
      north: [4, 5, 6, 7, 8],
      south: [0, 1, 2, 10, 11],
    },
    times: [{ from: 8, to: 19 }],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-39",
    category: "bug",
    name: "Diving Beetle",
    location: "On Rivers",
    shadow: null,
    price: 800,
    months: {
      north: [4, 5, 6, 7, 8],
      south: [0, 1, 2, 10, 11],
    },
    times: [{ from: 8, to: 19 }],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-40",
    category: "bug",
    name: "Giant Water Bug",
    location: "On Rivers",
    shadow: null,
    price: 2000,
    months: {
      north: [3, 4, 5, 6, 7, 8],
      south: [0, 1, 2, 9, 10, 11],
    },
    times: [
      { from: 0, to: 8 },
      { from: 19, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "b-41",
    category: "bug",
    name: "Stinkbug",
    location: "On Flowers",
    shadow: null,
    price: 120,
    months: {
      north: [2, 3, 4, 5, 6, 7, 8, 9],
      south: [0, 1, 2, 3, 8, 9, 10, 11],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "b-42",
    category: "bug",
    name: "Man-faced Stink Bug",
    location: "On Flowers",
    shadow: null,
    price: 1000,
    months: {
      north: [2, 3, 4, 5, 6, 7, 8, 9],
      south: [0, 1, 2, 3, 8, 9, 10, 11],
    },
    times: [
      { from: 0, to: 8 },
      { from: 19, to: 24 },
    ],
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-43",
    category: "bug",
    name: "Ladybug",
    location: "On Flowers",
    shadow: null,
    price: 200,
    months: {
      north: [2, 3, 4, 5, 9],
      south: [3, 8, 9, 10, 11],
    },
    times: [{ from: 8, to: 17 }],
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-44",
    category: "bug",
    name: "Tiger Beetle",
    location: "Ground",
    shadow: null,
    price: 1500,
    months: {
      north: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      south: [0, 1, 2, 3, 7, 8, 9, 10, 11],
    },
    times: null,
    rainOnly: false,
    rainHide: true,
    rarity: 3,
  },
  {
    cpId: "b-45",
    category: "bug",
    name: "Jewel Beetle",
    location: "Tree Stumps",
    shadow: null,
    price: 2400,
    months: {
      north: [3, 4, 5, 6, 7],
      south: [0, 1, 9, 10, 11],
    },
    times: null,
    rainOnly: false,
    rainHide: true,
    rarity: 2,
  },
  {
    cpId: "b-46",
    category: "bug",
    name: "Violin Beetle",
    location: "Tree Stumps",
    shadow: null,
    price: 450,
    months: {
      north: [4, 5, 8, 9, 10],
      south: [2, 3, 4, 10, 11],
    },
    times: null,
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-47",
    category: "bug",
    name: "Citrus Long-Horned Beetle",
    location: "Tree Stumps",
    shadow: null,
    price: 350,
    months: null,
    times: null,
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-48",
    category: "bug",
    name: "Rosalia Batesi Beetle",
    location: "Tree Stumps",
    shadow: null,
    price: 3000,
    months: {
      north: [4, 5, 6, 7, 8],
      south: [0, 1, 2, 10, 11],
    },
    times: null,
    rainOnly: false,
    rainHide: true,
    rarity: 2,
  },
  {
    cpId: "b-49",
    category: "bug",
    name: "Blue Weevil Beetle",
    location: "On Palm Tree",
    shadow: null,
    price: 800,
    months: {
      north: [6, 7],
      south: [0, 1],
    },
    times: null,
    rainOnly: false,
    rainHide: true,
    rarity: 3,
  },
  {
    cpId: "b-50",
    category: "bug",
    name: "Dung Beetle",
    location: "Near Snowballs",
    shadow: null,
    price: 3000,
    months: {
      north: [0, 1, 11],
      south: [5, 6, 7],
    },
    times: null,
    rainOnly: false,
    rainHide: true,
    rarity: 2,
  },
  {
    cpId: "b-51",
    category: "bug",
    name: "Earth-Boring Dung Beetle",
    location: "Ground",
    shadow: null,
    price: 300,
    months: {
      north: [6, 7, 8],
      south: [0, 1, 2],
    },
    times: null,
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-52",
    category: "bug",
    name: "Scarab Beetle",
    location: "On Trees",
    shadow: null,
    price: 10000,
    months: {
      north: [6, 7],
      south: [0, 1],
    },
    times: [
      { from: 0, to: 8 },
      { from: 23, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 3,
  },
  {
    cpId: "b-53",
    category: "bug",
    name: "Drone Beetle",
    location: "Trees",
    shadow: null,
    price: 200,
    months: {
      north: [5, 6, 7],
      south: [0, 1, 11],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-54",
    category: "bug",
    name: "Goliath Beetle",
    location: "On Palm Trees",
    shadow: null,
    price: 8000,
    months: {
      north: [5, 6, 7, 8],
      south: [0, 1, 2, 11],
    },
    times: [
      { from: 0, to: 8 },
      { from: 17, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 4,
  },
  {
    cpId: "b-55",
    category: "bug",
    name: "Saw Stag",
    location: "On Trees",
    shadow: null,
    price: 2000,
    months: {
      north: [6, 7],
      south: [0, 1],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "b-56",
    category: "bug",
    name: "Miyama Stag",
    location: "On Trees",
    shadow: null,
    price: 1000,
    months: {
      north: [6, 7],
      south: [0, 1],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-57",
    category: "bug",
    name: "Giant Stag",
    location: "On Trees",
    shadow: null,
    price: 10000,
    months: {
      north: [6, 7],
      south: [0, 1],
    },
    times: [
      { from: 0, to: 8 },
      { from: 23, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 3,
  },
  {
    cpId: "b-58",
    category: "bug",
    name: "Rainbow Stag",
    location: "On Trees",
    shadow: null,
    price: 6000,
    months: {
      north: [5, 6, 7, 8],
      south: [0, 1, 2, 11],
    },
    times: [
      { from: 0, to: 8 },
      { from: 19, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 3,
  },
  {
    cpId: "b-59",
    category: "bug",
    name: "Cyclommatus Stag",
    location: "Palm Trees",
    shadow: null,
    price: 8000,
    months: {
      north: [6, 7],
      south: [0, 1],
    },
    times: [
      { from: 0, to: 4 },
      { from: 17, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 4,
  },
  {
    cpId: "b-60",
    category: "bug",
    name: "Golden Stag",
    location: "On Palm Trees",
    shadow: null,
    price: 12000,
    months: {
      north: [6, 7],
      south: [0, 1],
    },
    times: [
      { from: 0, to: 8 },
      { from: 17, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 5,
  },
  {
    cpId: "b-61",
    category: "bug",
    name: "Giraffe Stag",
    location: "On Palm Trees",
    shadow: null,
    price: 12000,
    months: {
      north: [6, 7],
      south: [0, 1],
    },
    times: [
      { from: 0, to: 8 },
      { from: 17, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 4,
  },
  {
    cpId: "b-62",
    category: "bug",
    name: "Horned Dynastid",
    location: "On Trees",
    shadow: null,
    price: 1350,
    months: {
      north: [6, 7],
      south: [0, 1],
    },
    times: [
      { from: 0, to: 8 },
      { from: 17, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-63",
    category: "bug",
    name: "Horned Atlas",
    location: "On Palm Trees",
    shadow: null,
    price: 8000,
    months: {
      north: [6, 7],
      south: [0, 1],
    },
    times: [
      { from: 0, to: 8 },
      { from: 17, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 4,
  },
  {
    cpId: "b-64",
    category: "bug",
    name: "Horned Elephant",
    location: "On Palm Trees",
    shadow: null,
    price: 8000,
    months: {
      north: [6, 7],
      south: [0, 1],
    },
    times: [
      { from: 0, to: 8 },
      { from: 17, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 4,
  },
  {
    cpId: "b-65",
    category: "bug",
    name: "Horned Hercules",
    location: "On Palm Trees",
    shadow: null,
    price: 12000,
    months: {
      north: [6, 7],
      south: [0, 1],
    },
    times: [
      { from: 0, to: 8 },
      { from: 17, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 5,
  },
  {
    cpId: "b-66",
    category: "bug",
    name: "Walking Stick",
    location: "Trees",
    shadow: null,
    price: 600,
    months: {
      north: [6, 7, 8, 9, 10],
      south: [0, 1, 2, 3, 4],
    },
    times: [
      { from: 4, to: 8 },
      { from: 17, to: 19 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "b-67",
    category: "bug",
    name: "Walking Leaf",
    location: "Trees",
    shadow: null,
    price: 600,
    months: {
      north: [6, 7, 8],
      south: [0, 1, 2],
    },
    times: null,
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-68",
    category: "bug",
    name: "Bagworm",
    location: "Shaking Trees",
    shadow: null,
    price: 600,
    months: null,
    times: null,
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-69",
    category: "bug",
    name: "Ant",
    location: "Turnips",
    shadow: null,
    price: 80,
    months: null,
    times: null,
    rainOnly: false,
    rainHide: true,
    rarity: 1,
  },
  {
    cpId: "b-70",
    category: "bug",
    name: "Hermit Crab",
    location: "On The Shore",
    shadow: null,
    price: 100,
    months: null,
    times: [
      { from: 0, to: 8 },
      { from: 19, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-71",
    category: "bug",
    name: "Wharf Roach",
    location: "Shore Rocks",
    shadow: null,
    price: 200,
    months: null,
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-72",
    category: "bug",
    name: "Fly",
    location: "On Garbage",
    shadow: null,
    price: 60,
    months: null,
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-73",
    category: "bug",
    name: "Mosquito",
    location: "Flying",
    shadow: null,
    price: 130,
    months: {
      north: [5, 6, 7, 8],
      south: [0, 1, 2, 11],
    },
    times: [
      { from: 0, to: 4 },
      { from: 17, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-74",
    category: "bug",
    name: "Flea",
    location: "On Villager",
    shadow: null,
    price: 70,
    months: {
      north: [3, 4, 5, 6, 7, 8, 9, 10],
      south: [0, 1, 2, 3, 4, 9, 10, 11],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-75",
    category: "bug",
    name: "Snail",
    location: "Rocks/Hedges",
    shadow: null,
    price: 250,
    months: null,
    times: null,
    rainOnly: true,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-76",
    category: "bug",
    name: "Pill Bug",
    location: "Hit Rocks",
    shadow: null,
    price: 250,
    months: {
      north: [0, 1, 2, 3, 4, 5, 8, 9, 10, 11],
      south: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    },
    times: [
      { from: 0, to: 16 },
      { from: 23, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-77",
    category: "bug",
    name: "Centipede",
    location: "Hit Rocks",
    shadow: null,
    price: 300,
    months: {
      north: [0, 1, 2, 3, 4, 5, 8, 9, 10, 11],
      south: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    },
    times: [
      { from: 0, to: 16 },
      { from: 23, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-78",
    category: "bug",
    name: "Spider",
    location: "Shake Trees",
    shadow: null,
    price: 600,
    months: null,
    times: [
      { from: 0, to: 8 },
      { from: 19, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "b-79",
    category: "bug",
    name: "Tarantula",
    location: "Ground",
    shadow: null,
    price: 8000,
    months: {
      north: [0, 1, 2, 3, 10, 11],
      south: [4, 5, 6, 7, 8, 9],
    },
    times: [
      { from: 0, to: 4 },
      { from: 19, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 4,
  },
  {
    cpId: "b-80",
    category: "bug",
    name: "Scorpion",
    location: "Ground",
    shadow: null,
    price: 8000,
    months: {
      north: [4, 5, 6, 7, 8, 9],
      south: [0, 1, 2, 3, 10, 11],
    },
    times: [
      { from: 0, to: 4 },
      { from: 19, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 4,
  },
  // fish
  {
    cpId: "f-1",
    category: "fish",
    name: "Bitterling",
    location: "River",
    shadow: "tiny",
    price: 900,
    months: null,
    times: [{ from: 9, to: 16 }],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "f-2",
    category: "fish",
    name: "Pale Chub",
    location: "River",
    shadow: "tiny",
    price: 200,
    months: null,
    times: [{ from: 9, to: 16 }],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "f-3",
    category: "fish",
    name: "Crucian Carp",
    location: "River",
    shadow: "small",
    price: 160,
    months: null,
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "f-4",
    category: "fish",
    name: "Dace",
    location: "River",
    shadow: "medium",
    price: 240,
    months: null,
    times: [
      { from: 0, to: 9 },
      { from: 16, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "f-5",
    category: "fish",
    name: "Carp",
    location: "Pond",
    shadow: "large",
    price: 300,
    months: null,
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "f-6",
    category: "fish",
    name: "Koi",
    location: "Pond",
    shadow: "large",
    price: 4000,
    months: null,
    times: [
      { from: 0, to: 9 },
      { from: 16, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "f-7",
    category: "fish",
    name: "Goldfish",
    location: "Pond",
    shadow: "tiny",
    price: 1300,
    months: null,
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "f-8",
    category: "fish",
    name: "Pop-eyed Goldfish",
    location: "Pond",
    shadow: "tiny",
    price: 1300,
    months: null,
    times: [{ from: 9, to: 16 }],
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "f-9",
    category: "fish",
    name: "Ranchu Goldfish",
    location: "Pond",
    shadow: "small",
    price: 4500,
    months: null,
    times: [{ from: 9, to: 16 }],
    rainOnly: false,
    rainHide: false,
    rarity: 4,
  },
  {
    cpId: "f-10",
    category: "fish",
    name: "Killifish",
    location: "Pond",
    shadow: "tiny",
    price: 300,
    months: {
      north: [3, 4, 5, 6, 7],
      south: [0, 1, 9, 10, 11],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "f-11",
    category: "fish",
    name: "Crawfish",
    location: "Pond",
    shadow: "tiny",
    price: 200,
    months: {
      north: [3, 4, 5, 6, 7, 8],
      south: [0, 1, 2, 9, 10, 11],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "f-12",
    category: "fish",
    name: "Soft Shelled Turtle",
    location: "River",
    shadow: "medium",
    price: 3750,
    months: {
      north: [3, 4, 5, 6, 7],
      south: [0, 1, 9, 10, 11],
    },
    times: [
      { from: 0, to: 9 },
      { from: 16, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 3,
  },
  {
    cpId: "f-13",
    category: "fish",
    name: "Snapping Turtle",
    location: "River",
    shadow: "medium",
    price: 5000,
    months: {
      north: [3, 4, 5, 6, 7, 8, 9],
      south: [0, 1, 2, 3, 9, 10, 11],
    },
    times: [
      { from: 0, to: 9 },
      { from: 16, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "f-14",
    category: "fish",
    name: "Tadpole",
    location: "Pond",
    shadow: "tiny",
    price: 100,
    months: {
      north: [2, 3, 4, 5, 6],
      south: [0, 8, 9, 10, 11],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "f-15",
    category: "fish",
    name: "Frog",
    location: "Pond",
    shadow: "small",
    price: 120,
    months: {
      north: [4, 5, 6, 7],
      south: [0, 1, 10, 11],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "f-16",
    category: "fish",
    name: "Freshwater Goby",
    location: "River",
    shadow: "small",
    price: 400,
    months: null,
    times: [
      { from: 0, to: 9 },
      { from: 16, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "f-17",
    category: "fish",
    name: "Loach",
    location: "River",
    shadow: "small",
    price: 400,
    months: {
      north: [2, 3, 4],
      south: [8, 9, 10],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "f-18",
    category: "fish",
    name: "Catfish",
    location: "Pond",
    shadow: "large",
    price: 800,
    months: {
      north: [4, 5, 6, 7, 8, 9],
      south: [0, 1, 2, 3, 10, 11],
    },
    times: [
      { from: 0, to: 9 },
      { from: 16, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "f-19",
    category: "fish",
    name: "Giant Snakehead",
    location: "Pond",
    shadow: "large",
    price: 5500,
    months: {
      north: [5, 6, 7],
      south: [0, 1, 11],
    },
    times: [{ from: 9, to: 16 }],
    rainOnly: false,
    rainHide: false,
    rarity: 4,
  },
  {
    cpId: "f-20",
    category: "fish",
    name: "Bluegill",
    location: "Pond",
    shadow: "small",
    price: 160,
    months: null,
    times: [{ from: 9, to: 16 }],
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "f-21",
    category: "fish",
    name: "Yellow Perch",
    location: "River",
    shadow: "medium",
    price: 300,
    months: {
      north: [0, 1, 2, 9, 10, 11],
      south: [3, 4, 5, 6, 7, 8],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 4,
  },
  {
    cpId: "f-22",
    category: "fish",
    name: "Black Bass",
    location: "River",
    shadow: "large",
    price: 400,
    months: null,
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 0,
  },
  {
    cpId: "f-23",
    category: "fish",
    name: "Tilapia",
    location: "River",
    shadow: "medium",
    price: 800,
    months: {
      north: [5, 6, 7, 8, 9],
      south: [0, 1, 2, 3, 11],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "f-24",
    category: "fish",
    name: "Pike",
    location: "River",
    shadow: "large",
    price: 1800,
    months: {
      north: [8, 9, 10, 11],
      south: [2, 3, 4, 5],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "f-25",
    category: "fish",
    name: "Pond Smelt",
    location: "River",
    shadow: "small",
    price: 400,
    months: {
      north: [0, 1, 11],
      south: [5, 6, 7],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "f-26",
    category: "fish",
    name: "Sweetfish",
    location: "River",
    shadow: "medium",
    price: 900,
    months: {
      north: [6, 7, 8],
      south: [0, 1, 2],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "f-27",
    category: "fish",
    name: "Cherry Salmon",
    location: "Cliffs",
    shadow: "medium",
    price: 1000,
    months: {
      north: [2, 3, 4, 5],
      south: [8, 9, 10, 11],
    },
    times: [
      { from: 0, to: 9 },
      { from: 16, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 3,
  },
  {
    cpId: "f-28",
    category: "fish",
    name: "Char",
    location: "Cliffs",
    shadow: "large",
    price: 3800,
    months: {
      north: [2, 3, 4, 5],
      south: [8, 9, 10, 11],
    },
    times: [
      { from: 0, to: 9 },
      { from: 16, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 5,
  },
  {
    cpId: "f-29",
    category: "fish",
    name: "Golden Trout",
    location: "Cliff",
    shadow: "medium",
    price: 15000,
    months: {
      north: [2, 3, 4, 8, 9, 10],
      south: [2, 3, 4, 8, 9, 10],
    },
    times: [
      { from: 0, to: 9 },
      { from: 16, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 4,
  },
  {
    cpId: "f-30",
    category: "fish",
    name: "Stringfish",
    location: "Cliff",
    shadow: "huge",
    price: 15000,
    months: {
      north: [0, 1, 2, 11],
      south: [5, 6, 7, 8],
    },
    times: [
      { from: 0, to: 9 },
      { from: 16, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 5,
  },

  {
    cpId: "f-31",
    category: "fish",
    name: "Salmon",
    location: "River Mouth",
    shadow: "large",
    price: 700,
    months: {
      north: [8],
      south: [2],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "f-32",
    category: "fish",
    name: "King Salmon",
    location: "River Mouth",
    shadow: "huge",
    price: 1800,
    months: {
      north: [8],
      south: [2],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 3,
  },
  {
    cpId: "f-33",
    category: "fish",
    name: "Mitten Crab",
    location: "River",
    shadow: "small",
    price: 2000,
    months: {
      north: [10],
      south: [4],
    },
    times: [
      { from: 0, to: 9 },
      { from: 16, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 3,
  },
  {
    cpId: "f-52",
    category: "fish",
    name: "Napoleonfish",
    location: "Sea",
    shadow: "huge",
    price: 10000,
    months: {
      north: [6, 7],
      south: [0, 1],
    },
    times: [{ from: 4, to: 21 }],
    rainOnly: false,
    rainHide: false,
    rarity: 3,
  },
  {
    cpId: "f-80",
    category: "fish",
    name: "Coelacanth",
    location: "Sea",
    shadow: "huge",
    price: 15000,
    months: null,
    times: null,
    rainOnly: true,
    rainHide: false,
    rarity: 4,
  },
  // sea creatures
  {
    cpId: "s-1",
    category: "sea",
    name: "Seaweed",
    location: "Sea",
    shadow: "large",
    price: 600,
    months: {
      north: [0, 1, 2, 3, 4, 5, 6, 9, 10, 11],
      south: [0, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 0,
  },
  {
    cpId: "s-2",
    category: "sea",
    name: "Sea Grapes",
    location: "Sea",
    shadow: "medium",
    price: 900,
    months: {
      north: [5, 6, 7, 8],
      south: [0, 1, 2, 11],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 0,
  },
  {
    cpId: "s-3",
    category: "sea",
    name: "Sea Cucumber",
    location: "Sea",
    shadow: "large",
    price: 500,
    months: {
      north: [0, 1, 2, 3, 10, 11],
      south: [4, 5, 6, 7, 8, 9],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "s-4",
    category: "sea",
    name: "Sea Pig",
    location: "Sea",
    shadow: "medium",
    price: 10000,
    months: {
      north: [0, 1, 10, 11],
      south: [4, 5, 6, 7],
    },
    times: [{ from: 16, to: 21 }],
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "s-5",
    category: "sea",
    name: "Sea Star",
    location: "Sea",
    shadow: "medium",
    price: 500,
    months: null,
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "s-6",
    category: "sea",
    name: "Sea Urchin",
    location: "Sea",
    shadow: "medium",
    price: 1700,
    months: {
      north: [4, 5, 6, 7, 8],
      south: [0, 1, 2, 10, 11],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "s-7",
    category: "sea",
    name: "Slate Pencil Urchin",
    location: "Sea",
    shadow: "large",
    price: 2000,
    months: {
      north: [4, 5, 6, 7, 8],
      south: [0, 1, 2, 10, 11],
    },
    times: [{ from: 16, to: 21 }],
    rainOnly: false,
    rainHide: false,
    rarity: 3,
  },
  {
    cpId: "s-8",
    category: "sea",
    name: "Sea Anemone",
    location: "Sea",
    shadow: "medium",
    price: 500,
    months: null,
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "s-9",
    category: "sea",
    name: "Moon Jellyfish",
    location: "Sea",
    shadow: "medium",
    price: 600,
    months: {
      north: [6, 7, 8],
      south: [0, 1, 2],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "s-10",
    category: "sea",
    name: "Sea Slug",
    location: "Sea",
    shadow: "small",
    price: 600,
    months: null,
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "s-11",
    category: "sea",
    name: "Pearl Oyster",
    location: "Sea",
    shadow: "medium",
    price: 2800,
    months: null,
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "s-12",
    category: "sea",
    name: "Mussel",
    location: "Sea",
    shadow: "medium",
    price: 1500,
    months: {
      north: [5, 6, 7, 8, 9, 10, 11],
      south: [0, 1, 2, 3, 4, 5, 11],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "s-13",
    category: "sea",
    name: "Oyster",
    location: "Sea",
    shadow: "small",
    price: 1100,
    months: {
      north: [0, 1, 8, 9, 10, 11],
      south: [2, 3, 4, 5, 6, 7],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "s-14",
    category: "sea",
    name: "Scallop",
    location: "Sea",
    shadow: "medium",
    price: 1200,
    months: null,
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "s-15",
    category: "sea",
    name: "Whelk",
    location: "Sea",
    shadow: "small",
    price: 1000,
    months: null,
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "s-16",
    category: "sea",
    name: "Turban Shell",
    location: "Sea",
    shadow: "small",
    price: 1000,
    months: {
      north: [2, 3, 4, 8, 9, 10, 11],
      south: [2, 3, 4, 5, 8, 9, 10],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "s-17",
    category: "sea",
    name: "Abalone",
    location: "Sea",
    shadow: "medium",
    price: 2000,
    months: {
      north: [0, 5, 6, 7, 8, 9, 10, 11],
      south: [0, 1, 2, 3, 4, 5, 6, 11],
    },
    times: [
      { from: 0, to: 9 },
      { from: 16, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 3,
  },
  {
    cpId: "s-18",
    category: "sea",
    name: "Giant Gigas Clam",
    location: "Sea",
    shadow: "small",
    price: 15000,
    months: {
      north: [4, 5, 6, 7, 8],
      south: [0, 1, 2, 10, 11],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 5,
  },
  {
    cpId: "s-19",
    category: "sea",
    name: "Chambered Nautilus",
    location: "Sea",
    shadow: "large",
    price: 1800,
    months: {
      north: [2, 3, 4, 5, 8, 9, 10],
      south: [2, 3, 4, 8, 9, 10, 11],
    },
    times: [
      { from: 0, to: 9 },
      { from: 16, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "s-20",
    category: "sea",
    name: "Octopus",
    location: "Sea",
    shadow: "large",
    price: 1200,
    months: null,
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "s-21",
    category: "sea",
    name: "Umbrella Octopus",
    location: "Sea",
    shadow: "medium",
    price: 6000,
    months: {
      north: [2, 3, 4, 8, 9, 10],
      south: [2, 3, 4, 8, 9, 10],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 4,
  },
  {
    cpId: "s-22",
    category: "sea",
    name: "Vampire Squid",
    location: "Sea",
    shadow: "large",
    price: 10000,
    months: {
      north: [4, 5, 6, 7],
      south: [0, 1, 10, 11],
    },
    times: [
      { from: 0, to: 9 },
      { from: 16, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 4,
  },
  {
    cpId: "s-23",
    category: "sea",
    name: "Firefly Squid",
    location: "Sea",
    shadow: "small",
    price: 1400,
    months: {
      north: [2, 3, 4, 5],
      south: [8, 9, 10, 11],
    },
    times: [
      { from: 0, to: 4 },
      { from: 21, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 3,
  },
  {
    cpId: "s-24",
    category: "sea",
    name: "Gazami Crab",
    location: "Sea",
    shadow: "large",
    price: 2200,
    months: {
      north: [5, 6, 7, 8, 9, 10],
      south: [0, 1, 2, 3, 4, 11],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "s-25",
    category: "sea",
    name: "Dungeness Crab",
    location: "Sea",
    shadow: "large",
    price: 1900,
    months: {
      north: [0, 1, 2, 3, 4, 10, 11],
      south: [4, 5, 6, 7, 8, 9, 10],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "s-26",
    category: "sea",
    name: "Snow Crab",
    location: "Sea",
    shadow: "large",
    price: 6000,
    months: {
      north: [0, 1, 2, 3, 10, 11],
      south: [4, 5, 6, 7, 8, 9],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 3,
  },
  {
    cpId: "s-27",
    category: "sea",
    name: "Red King Crab",
    location: "Sea",
    shadow: "large",
    price: 8000,
    months: {
      north: [0, 1, 2, 10, 11],
      south: [5, 6, 7, 8, 9],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 3,
  },
  {
    cpId: "s-28",
    category: "sea",
    name: "Acorn Barnacle",
    location: "Sea",
    shadow: "large",
    price: 600,
    months: null,
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "s-29",
    category: "sea",
    name: "Spider Crab",
    location: "Sea",
    shadow: "large",
    price: 10000,
    months: {
      north: [2, 3],
      south: [8, 9],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 5,
  },
  {
    cpId: "s-30",
    category: "sea",
    name: "Tiger Prawn",
    location: "Sea",
    shadow: "medium",
    price: 3000,
    months: {
      north: [5, 6, 7, 8],
      south: [0, 1, 2, 11],
    },
    times: [
      { from: 0, to: 9 },
      { from: 16, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 3,
  },
  {
    cpId: "s-31",
    category: "sea",
    name: "Sweet Shrimp",
    location: "Sea",
    shadow: "medium",
    price: 1400,
    months: {
      north: [0, 1, 8, 9, 10, 11],
      south: [2, 3, 4, 5, 6, 7],
    },
    times: [
      { from: 0, to: 9 },
      { from: 16, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "s-32",
    category: "sea",
    name: "Mantis Shrimp",
    location: "Sea",
    shadow: "medium",
    price: 2500,
    months: null,
    times: [
      { from: 0, to: 9 },
      { from: 16, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 2,
  },
  {
    cpId: "s-33",
    category: "sea",
    name: "Spiny Lobster",
    location: "Sea",
    shadow: "large",
    price: 3000,
    months: {
      north: [9, 10, 11],
      south: [4, 5, 6],
    },
    times: [
      { from: 0, to: 4 },
      { from: 21, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 4,
  },
  {
    cpId: "s-34",
    category: "sea",
    name: "Lobster",
    location: "Sea",
    shadow: "large",
    price: 4500,
    months: {
      north: [0, 3, 4, 5, 11],
      south: [5, 6, 9, 10, 11],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 4,
  },
  {
    cpId: "s-35",
    category: "sea",
    name: "Giant Isopod",
    location: "Sea",
    shadow: "large",
    price: 9000,
    months: {
      north: [5, 6, 7, 8],
      south: [0, 1, 2, 3],
    },
    times: [
      { from: 0, to: 4 },
      { from: 9, to: 16 },
      { from: 21, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 4,
  },
  {
    cpId: "s-36",
    category: "sea",
    name: "Horseshoe Crab",
    location: "Sea",
    shadow: "medium",
    price: 1500,
    months: {
      north: [3, 4, 5, 6, 7],
      south: [0, 1, 9, 10, 11],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 4,
  },
  {
    cpId: "s-37",
    category: "sea",
    name: "Sea Pineapple",
    location: "Sea",
    shadow: "large",
    price: 1500,
    months: {
      north: [6, 7, 8],
      south: [0, 1, 2],
    },
    times: [
      { from: 0, to: 4 },
      { from: 21, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 1,
  },
  {
    cpId: "s-38",
    category: "sea",
    name: "Spotted Garden Eel",
    location: "Sea",
    shadow: "medium",
    price: 1100,
    months: {
      north: [5, 6, 7, 8, 9, 10],
      south: [0, 1, 2, 3, 10, 11],
    },
    times: [
      { from: 0, to: 4 },
      { from: 21, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 4,
  },
  {
    cpId: "s-39",
    category: "sea",
    name: "Flatworm",
    location: "Sea",
    shadow: "small",
    price: 200,
    months: {
      north: [7, 8],
      south: [1, 2],
    },
    times: [
      { from: 0, to: 9 },
      { from: 16, to: 24 },
    ],
    rainOnly: false,
    rainHide: false,
    rarity: 4,
  },
  {
    cpId: "s-40",
    category: "sea",
    name: "Venus' Flower Basket",
    location: "Sea",
    shadow: "medium",
    price: 5000,
    months: {
      north: [0, 1, 9, 10, 11],
      south: [3, 4, 5, 6, 7],
    },
    times: null,
    rainOnly: false,
    rainHide: false,
    rarity: 5,
  },
];
